# Generated by Django 5.0.6 on 2024-07-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
