# Generated by Django 5.0.6 on 2024-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_roomtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
